include $(THEOS)/makefiles/common.mk

TWEAK_NAME = GlowR4
GlowR4_FILES = Tweak.x
GlowR4_FRAMEWORKS = UIKit
GlowR4_CFLAGS = -fobjc-arc -Wno-error
GlowR4_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries

include $(THEOS)/makefiles/tweak.mk
