name: Build Glow from Source

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        uses: waruhachi/theos-action@v2.4.6
      - name: Build Glow
        run: |
          cd glow-from-source
          make clean package FINALPACKAGE=1
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: glow-from-source-deb
          path: glow-from-source/packages/*.deb
